app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

brands/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

outflows/models.py
from django.db import models
from products.models import Product


class Outflow(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='outflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

products/models.py
from django.db import models
from categories.models import Category
from brands.models import Brand


class Product(models.Model):
    title = models.CharField(max_length=500)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='products')
    description = models.TextField(null=True, blank=True)
    serie_number = models.CharField(max_length=200, null=True, blank=True)
    cost_price = models.DecimalField(max_digits=20, decimal_places=2)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

inflows/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, DetailView
from django.urls import reverse_lazy
from . import models, forms, serializers


class InflowListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Inflow
    template_name = 'inflow_list.html'
    context_object_name = 'inflows'
    paginate_by = 10
    permission_required = 'inflows.view_inflow'

    def get_queryset(self):
        queryset = super().get_queryset()
        product = self.request.GET.get('product')

        if product:
            queryset = queryset.filter(product__title__icontains=product)

        return queryset


class InflowCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Inflow
    template_name = 'inflow_create.html'
    form_class = forms.InflowForm
    success_url = reverse_lazy('inflow_list')
    permission_required = 'inflows.add_inflow'


class InflowDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Inflow
    template_name = 'inflow_detail.html'
    permission_required = 'inflows.view_inflow'


class InflowCreateListApiView(generics.ListCreateAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer


class InflowRetrieveApiView(generics.RetrieveAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer

app/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
    <span class="text-muted">© 2025 SGE</span>
  </div>
</footer>

app/templates/components/_header.html
<nav class="navbar navbar-expand-md py-1"> <!--Barra de navegação-->
	<div class="container-fluid">
		<a href="" class="navbar-brand d-flex align-items-center">
			<i class="bi bi-box2 fs-1 me-2"></i>
			Gestão de Estoque
		</a>
		{% if user.is_authenticated %}
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menuNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse me-1" id="menuNavbar">
			<div class="navbar-nav ms-auto">
				<a href="{% url 'home' %}" class="nav-link"><i class="bi bi-house"></i> Home</a>
				<div class="dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-arrow-down-up"></i>
						Movimento</a>
					<ul class="dropdown-menu dropdown-menu-end">
						{% if perms.inflows.view_inflow %}
							<li><a href="{% url 'inflow_list' %}" class="dropdown-item"><i class="bi bi-arrow-up"></i> Entradas</a></li>
						{% endif %}
						
						{% if perms.outflows.view_outflow %}
							<li><a href="{% url 'outflow_list' %}" class="dropdown-item"><i class="bi bi-arrow-down"></i> Saídas</a></li>
						{% endif %}
					</ul>
				</div>
				<div class="dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-ui-checks-grid"></i>
						Cadastros</a>
					<ul class="dropdown-menu">
						{% if perms.products.view_product %}
							<li><a href="{% url 'product_list' %}" class="dropdown-item"><i class="bi bi-basket"></i> Produtos</a></li>
						{% endif %}

						{% if perms.brands.view_brand %}
							<li><a href="{% url 'brand_list' %}" class="dropdown-item"><i class="bi bi-shop"> </i>Marcas</a></li>
						{% endif %}
						
						{% if perms.categories.view_category %}
							<li><a href="{% url 'category_list' %}" class="dropdown-item"><i class="bi bi-tags"></i> Categorias</a></li>
						{% endif %}
						
						{% if perms.suppliers.view_supplier %}
							<li><a href="{% url 'supplier_list' %}" class="dropdown-item"><i class="bi bi-truck"></i> Fornecedores</a></li>
						{% endif %}
					</ul>
				</div>
				<div class="dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-person-circle"></i></a>
					<ul class="dropdown-menu dropdown-menu-end">
						<li><a href="#" class="dropdown-item">Trocar Senha</a></li>
						<li><a href="#" class="dropdown-item">Mudar tema</a></li>
						<li><a href="#" class="dropdown-item">Contato</a></li>
						<li>
							<hr class="dropdown-divider">
						</li>
						<li>
							{% if user.is_authenticated %}
							<form action="{% url 'logout' %}" method="POST" id="logou-form" class="px-1 align-middle">
								{% csrf_token %}
								<button type="submit" class="btn btn-link text-decoration-none text-reset align-middle">
									<i class="bi bi-box-arrow-right"></i><span> Sair</span>
								</button>
							</form>
							{% endif %}
						</li>
					</ul>
				</div>
			</div>
		</div>
		{% endif %}
	</div>
</nav>

app/templates/components/_pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            <i class="bi bi-chevron-double-left"></i>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <i class="bi bi-chevron-left"></i>
          </a>
        </li>
      {% endif %}

      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <i class="bi bi-chevron-right"></i>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            <i class="bi bi-chevron-double-right"></i>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

app/templates/components/_product_metrics.html
<div class="card mt-4">
	<div class="card-body">
		<div class="row">

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-primary-subtle">
					<div class="card-body">
						<h5 class="card-title">Qtd. de Produtos</h5>
						<p class="card-text font-wheight-bold fs-3">{{ product_metrics.total_quantity }}</p>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-danger-subtle">
					<div class="card-body">
						<h5 class="card-title">Custo do estoque</h5>
						<p class="card-text font-wheight-bold fs-3">R$ {{ product_metrics.total_cost_price }}</p>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-success-subtle">
					<div class="card-body">
						<h5 class="card-title">Valor do estoque</h5>
						<p class="card-text font-wheight-bold fs-3">R$ {{ product_metrics.total_selling_price }}</p>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-warning-subtle">
					<div class="card-body">
						<h5 class="card-title">Lucro do estoque</h5>
						<p class="card-text font-wheight-bold fs-3">R$ {{ product_metrics.total_profit }}</p>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

app/templates/components/_sales_metrics.html
<div class="card mt-4">
	<div class="card-body">
		<div class="row">

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-primary-subtle">
					<div class="card-body">
						<h5 class="card-title">Qtd. de Vendas</h5>
						<p class="card-text font-wheight-bold fs-3">{{ sales_metrics.total_sales}}</p>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-danger-subtle">
					<div class="card-body">
						<h5 class="card-title">Produtos vendidos</h5>
						<p class="card-text font-wheight-bold fs-3">{{ sales_metrics.total_products_sold }}</p>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-success-subtle">
					<div class="card-body">
						<h5 class="card-title">Valor das vendas</h5>
						<p class="card-text font-wheight-bold fs-3">R$ {{ sales_metrics.total_sales_value }}</p>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-3 my-2">
				<div class="card bg-warning-subtle">
					<div class="card-body">
						<h5 class="card-title">Lucro das vendas</h5>
						<p class="card-text font-wheight-bold fs-3">R$ {{ sales_metrics.total_sales_profit }}</p>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>